# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rcs-common"
  s.version = "8.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["ALoR"]
  s.date = "2011-12-28"
  s.description = "Common components for the RCS Backend"
  s.email = "alor@hackingteam.it"
  s.extra_rdoc_files = [
    "LICENSE.txt"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "Rakefile",
    "VERSION",
    "lib/rcs-common.rb",
    "lib/rcs-common/cgi.rb",
    "lib/rcs-common/crypt.rb",
    "lib/rcs-common/evidence.rb",
    "lib/rcs-common/evidence/addressbook.rb",
    "lib/rcs-common/evidence/application.rb",
    "lib/rcs-common/evidence/calendar.rb",
    "lib/rcs-common/evidence/call.rb",
    "lib/rcs-common/evidence/camera.rb",
    "lib/rcs-common/evidence/chat.rb",
    "lib/rcs-common/evidence/clibpoard.rb",
    "lib/rcs-common/evidence/common.rb",
    "lib/rcs-common/evidence/content/camera/001.jpg",
    "lib/rcs-common/evidence/content/mouse/001.jpg",
    "lib/rcs-common/evidence/content/mouse/002.jpg",
    "lib/rcs-common/evidence/content/mouse/003.jpg",
    "lib/rcs-common/evidence/content/mouse/004.jpg",
    "lib/rcs-common/evidence/content/print/001.jpg",
    "lib/rcs-common/evidence/content/snapshot/001.jpg",
    "lib/rcs-common/evidence/content/snapshot/002.jpg",
    "lib/rcs-common/evidence/content/snapshot/003.jpg",
    "lib/rcs-common/evidence/content/url/001.jpg",
    "lib/rcs-common/evidence/content/url/002.jpg",
    "lib/rcs-common/evidence/content/url/003.jpg",
    "lib/rcs-common/evidence/device.rb",
    "lib/rcs-common/evidence/download.rb",
    "lib/rcs-common/evidence/file.rb",
    "lib/rcs-common/evidence/filesystem.rb",
    "lib/rcs-common/evidence/info.rb",
    "lib/rcs-common/evidence/keylog.rb",
    "lib/rcs-common/evidence/location.rb",
    "lib/rcs-common/evidence/mailraw.rb",
    "lib/rcs-common/evidence/mouse.rb",
    "lib/rcs-common/evidence/password.rb",
    "lib/rcs-common/evidence/print.rb",
    "lib/rcs-common/evidence/snapshot.rb",
    "lib/rcs-common/evidence/url.rb",
    "lib/rcs-common/fixnum.rb",
    "lib/rcs-common/mime.rb",
    "lib/rcs-common/pascalize.rb",
    "lib/rcs-common/serializer.rb",
    "lib/rcs-common/sqlite3.rb",
    "lib/rcs-common/symbolize.rb",
    "lib/rcs-common/systemstatus.rb",
    "lib/rcs-common/temporary.rb",
    "lib/rcs-common/time.rb",
    "lib/rcs-common/trace.rb",
    "lib/rcs-common/trace.yaml",
    "lib/rcs-common/utf16le.rb",
    "rcs-common.gemspec",
    "test/helper.rb",
    "test/test_cgi.rb",
    "test/test_crypt.rb",
    "test/test_evidence.rb",
    "test/test_evidence_manager.rb",
    "test/test_fixnum.rb",
    "test/test_mime.rb",
    "test/test_pascalize.rb",
    "test/test_rcs-common.rb",
    "test/test_serialization.rb",
    "test/test_symbolize.rb",
    "test/test_systemstatus.rb",
    "test/test_time.rb",
    "test/test_trace.rb",
    "test/test_utf16le.rb"
  ]
  s.homepage = "http://www.hackingteam.it"
  s.licenses = ["HT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "RCS Common components"
  s.test_files = [
    "test/helper.rb",
    "test/test_cgi.rb",
    "test/test_crypt.rb",
    "test/test_evidence.rb",
    "test/test_evidence_manager.rb",
    "test/test_fixnum.rb",
    "test/test_mime.rb",
    "test/test_pascalize.rb",
    "test/test_rcs-common.rb",
    "test/test_serialization.rb",
    "test/test_symbolize.rb",
    "test/test_systemstatus.rb",
    "test/test_time.rb",
    "test/test_trace.rb",
    "test/test_utf16le.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<log4r>, [">= 1.1.9"])
      s.add_runtime_dependency(%q<mime-types>, [">= 0"])
      s.add_runtime_dependency(%q<sys-filesystem>, [">= 0"])
      s.add_runtime_dependency(%q<sys-cpu>, [">= 0"])
      s.add_runtime_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<ffi>, [">= 0"])
      s.add_runtime_dependency(%q<mail>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<test-unit>, [">= 0"])
    else
      s.add_dependency(%q<log4r>, [">= 1.1.9"])
      s.add_dependency(%q<mime-types>, [">= 0"])
      s.add_dependency(%q<sys-filesystem>, [">= 0"])
      s.add_dependency(%q<sys-cpu>, [">= 0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<ffi>, [">= 0"])
      s.add_dependency(%q<mail>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<test-unit>, [">= 0"])
    end
  else
    s.add_dependency(%q<log4r>, [">= 1.1.9"])
    s.add_dependency(%q<mime-types>, [">= 0"])
    s.add_dependency(%q<sys-filesystem>, [">= 0"])
    s.add_dependency(%q<sys-cpu>, [">= 0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<ffi>, [">= 0"])
    s.add_dependency(%q<mail>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<test-unit>, [">= 0"])
  end
end

